bookr/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from bookr import settings
from .views import profile
import debug_toolbar

urlpatterns = [
    path('accounts/', include(('django.contrib.auth.urls', 'auth'), namespace='accounts')),
    path('accounts/profile/', profile, name="profile"),
    path('admin/', admin.site.urls),
    path('', include('reviews.urls')),
]

if settings.DEBUG:
    urlpatterns = [path('__debug__', include(debug_toolbar.urls))] + urlpatterns
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

reviews/urls.py
from django.urls import path, include
from .views import index, book_list, book_detail, book_search, publisher_edit, review_edit, book_media
from .api_views import BookViewSet, ReviewViewSet, Login
from rest_framework.routers import DefaultRouter

router = DefaultRouter()
router.register(r"books", BookViewSet)
router.register(r"reviews", ReviewViewSet)

urlpatterns = [
    path('', index, name='index'),
    path('books/', book_list, name='book_list'),
    path('books/<int:pk>/', book_detail, name="book_detail"),
    path('book-search/', book_search, name='book_search'),
    path('publishers/<int:pk>/', publisher_edit, name='publisher_edit'),
    path('publishers/new/', publisher_edit, name='publisher_create'),
    path('books/<book_pk>/reviews/new/', review_edit, name="review_create"),
    path('books/<book_pk>/reviews/<reviews_pk>/', review_edit, name="review_edit"),
    path('books/<int:pk>/media/', book_media, name="book_media"),
    path("api/", include((router.urls, "api"))),
    path("api/login/", Login.as_view(), name="login"),
]

templates/base.html
<!doctype html>
{% load static %}
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

    <link rel="stylesheet" href="{% static 'main.css' %}">

    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Libre+Baskerville|Source+Sans+Pro&display=swap">

    <title>{% block title %}Bookr{% endblock %}</title>
  </head>
  <body>
        <nav class="navbar navbar-expand-sm navbar-dark bg-dark sticky-top">
          <a class="navbar-brand" href="/">{% block brand %}<img src="{% static 'logo.png' %}">{% endblock %}</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
              <li class="nav-item active">
                <a class="nav-link" href="/books/">Strona główna <span class="sr-only">(current)</span></a>
              </li>
              {% if user.is_authenticated %}
              <li class="nav-item">
                <a class="nav-link" href="{% url 'accounts:logout' %}">Wyloguj</a>
              </li>
              {% else %}
              <li class="nav-item">
                <a class="nav-link" href="{% url 'accounts:login' %}">Zaloguj</a>
              </li>
              {% endif %}
            </ul>
            <form action="{% url 'book_search' %}" class="form-inline my-2 my-lg-0">
             <input class="form-control mr-sm-2" type="search" placeholder="Szukaj" aria-label="Search" name="search" value="{{ search_text }}" minlength="3">
              <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
            </form>
            {% if user.is_authenticated %}
              <a class="nav-link" href="{% url 'profile' %}">Użytkownik: {{ user.username }}</a>
            {% endif %}
          </div>
        </nav>
        <div class="container-fluid">
          {% for message in messages %}
            <div class="alert alert-{% if message.level_tag == 'error' %}danger{% else %}{{ message.level_tag }}{% endif %}" role="alert">
              {{ message }}
            </div>
          {% endfor %}
          {% block content %}
            <h1>Witaj w aplikacji Bookr!</h1>
           <h4>Ostatnie recenzje</h4>
          <div id="recent_reviews"></div>
          <script crossorigin src="https://unpkg.com/react@16/umd/react.development.js"></script>
          <script crossorigin src="https://unpkg.com/react-dom@16/umd/react-dom.development.js"></script>
          <script crossorigin src="https://unpkg.com/babel-standalone@6/babel.min.js"></script>
          <script src="{% static 'recent-reviews.js' %}" type="text/babel"></script>
          <script type="text/babel">
            ReactDOM.render(<RecentReviews url="{% url 'api:review-list' %}?limit=6" />,
                document.getElementById('recent_reviews')
            );
          </script>
          {% endblock %}
        </div>
  <!-- Copyright -->
  <footer class="page-footer font-small blue">
    <div class="footer-copyright text-center py-3">© 2020 Copyright:
      <a href="https://www.packtpub.com"> Packt Publications</a>
      <p>Website by: Packt Publications</p>
      <p>Contact information: <a href="mailto:email@example.com">email@example.com</a></p>
    </div>
  </footer>
  <!-- Copyright -->
  </body>
</html>

templates/profile.html
{% extends "base.html" %}

{% load profile_tags %}

{% block title %}Bookr{% endblock %}

{% block heading %}Profil{% endblock %}

{% block content %}
    <ul>
        <li>Nazwa użytkownika: {{ user.username }} </li>
        <li>Imię i nazwisko: {{ user.first_name }} {{ user.last_name }} </li>
        <li>Data dołączenia: {{ user.date_joined }} </li>
        <li>E-mail: {{ user.email }} </li>
        <li>Ostatni login: {{ user.last_login }} </li>
        <li>Grupy: {{ groups }}{% if not groups %}Brak{% endif %}</li>
    </ul>



{% endblock %}